services:
    postgres:
        container_name: postgres
        image: postgres:latest
        restart: always
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - '5433:5432'
        volumes:
            - postgres_data:/var/lib/postgresql
        networks:
            - backend
    redis:
        container_name: redis
        image: redis:6.2
        restart: always
        ports:
            - 6379:6379
        command: redis-server --requirepass ${REDIS_PASSWORD}
        volumes:
            - redis_data:/data
        networks:
            - backend
    mailpit:
        container_name: mailpit
        image: axllent/mailpit:latest
        restart: always
        ports:
            - '1025:1025' # SMTP
            - '8025:8025' # Web UI -> http://localhost:8025
        networks:
            - backend

volumes:
    postgres_data:
    redis_data:

networks:
    backend:
